customhost = "database-1.cut2mwwizarm.ap-south-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "spbk2023"
customregion = "us-east-2"
